VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITrades"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
option explicit

public idtrade as long
public dataentrada as date
public horaentrada as date
public corretora as string
public ativo as string
public estratégia as string
'public compravenda as string
'public ehdaytrade as boolean
'public precoentrada as double
'public nrocontratos as integer
'public precosl as double
'public preçotp as double
'public motivacaoentrada as string
'public datasaida as date
'public horasaida as date
'public precosaida as double
'public lucroprejuizo as double
'property get custocorretagem() as double
'
'end property
'property get custoemolumentos() as double
'
'end property
'property get margem() as double
'
'end property
'property get pontos() as double
'
'end property
'public motivacaosaida as string
'public mep as double
'public men as double
'public tipooperacao as string
'public tipoconta as string
'public fezprecomedio as boolean
'public revisartrade as boolean
'public trademental as boolean
'public condicaomercado as string
'public tipooportunidade as string
'public riscosempotencial as string
'public riscoentrada as string
'public riscosaida as string
'public gestaodotrade as string
'public imagem01 as string 'path
'public imagem02 as string 'path
'public observacoes as string
'public traderevisado as boolean
'public observacoesrevisao as string
'
'' propriedades de sistema
'public deleted as boolean
'public editado as date

